apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: CODE-VA-TEST-API
  description: The Benefits Claims API is a suite of services that enables VA and third-party consumers to build applications that let Veterans and their authorized representatives view and submit certain claims and claim-related information to the VA. We provide the ability to auto-establish claims by submitting structured data that can return realtime validations, allowing for better data quality.
  annotations:
    github.com/project-slug: https://github.com/department-of-veterans-affairs/vets-api
    datadog/production-monitor-id: '130917'
    datadog/sandbox-monitor-id: '130924' # status tab
    hub.lighthouse.va.gov/api-id: 'claims' # release notes tab
  title: CODE VA Test API
  tags:
    - lighthouse
    - external
  links:
    - url: https://developer.va.gov/explore/api/benefits-claims/docs?version=v1
      title: Public Docs
      icon: web
    - url: https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1663867462895/b0161ab939bba7d08f6bea07e3663d9d5cea22d4?sender=u9943b9a042c336e83bb20590
      title: Claim Status Data Flow Diagram
      icon: web
    - url: https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1663867462895/b0161ab939bba7d08f6bea07e3663d9d5cea22d4?sender=u9943b9a042c336e83bb20590
      title: ITF Process Flow Diagram
      icon: web
    - url: https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1663867462895/b0161ab939bba7d08f6bea07e3663d9d5cea22d4?sender=u9943b9a042c336e83bb20590
      title: 526EZ Process Flow Diagram
      icon: web
  va:
    maturity-markers:
      version: 1
      documentation:
      - noDocumentation
      - notPublic
      - legacyFormat
      - vaNetwork
      - public
      - openAPI
      architecture:
      - rest
      - soap
      - graphql
      - rpc
      lowerEnvironmentAccess:
      - moreThan2
      - lessThan2
      - auto
      productionAccess:
      - moreThan2
      - lessThan2
      - immediate
      performance:
      - notAvailable
      - p95Greater
      - p95Less
      - p99Less
      reliability:
      - notAvailable
      - notFollowing
      - sloExists
      - slo99
      - follow
      apiStatus:
      - notAvailable
      - noMetrics
      - noLogs
      - statusExists
      - statusHistoric
      - logs
      - metrics
      support:
      - notSupported
      - notMaintained
      - supportWithoutTeam
      - maintenanceLimited
      - supportedWithTeam
      - activelyMaintained
      hosting:
      - noCloud
      - cloudManual
      - cloudAuto
      testData:
      - notAvailable
      - testAvailable
      - testNotAvailable
spec:
  type: openapi
  lifecycle: production
  owner: lighthouse-dash
  system: vets-api
  definition:
    $text: https://github.com/department-of-veterans-affairs/vets-api/blob/master/modules/claims_api/app/swagger/claims_api/v1/swagger.json

