name: Create new MR
description: Create new maintenance request issue


inputs:
  gh-token:
    required: true
    description: Github token to use for api calls
  old-version:
    required: true
    description: The current version of the app ibeing supplanted in production  
  new-version:
    required: true
    description: The version of the app to deploy to production

runs:
  using: composite
  
  steps:
    
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup ENV values
      run: |
        echo "proposed_end_date_time=2023/11/21 12:30" >> $GITHUB_ENV
        echo "proposed_start_date_time=2023/11/21 12:15" >> $GITHUB_ENV
        echo "NEW_VERSION=${{ inputs.new-version}}" >> $GITHUB_ENV
        echo "OLD_VERSION=${{ inputs.old-version}}" >> $GITHUB_ENV
      shell: bash
    - name: Hydrate issue template 
      id: hydrate
      run: |
        body=$(cat ./.github/actions/create-maintenance-request/mr-body-template.md | sed -e 's/\b\_\_/${/g' -e 's/\_\_\b/}/g' | envsubst)
        echo "value<<EOF" >> $GITHUB_OUTPUT
        echo "$body" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT          
      shell: bash
    - name: Create the issue
      env:
        GITHUB_TOKEN: ${{ inputs.gh-token }}
      id: create-issue
      # Eventually add following (warning, they WILL start getting notifications if this is done!)
      # -f "assignees[]=sbair-va"
      # -f "assignees[]=beaugrantham-va"
      run: >
        gh api /repos/${{ github.repository }}/issues
        --method POST
        -f title='[MR] Promote Lighthouse Hub ${{ env.NEW_VERSION }} to Production (${{ env.proposed_start_date_time }} EST)'
        -f body='${{ steps.hydrate.outputs.value }}'
        -f "assignees[]=mhaley37"
        -f "labels[]=lhdi"        
        -f "labels[]=maintenance-request"
      shell: bash