name: Create new MR
description: Create new maintenance request issue


inputs:
  gh-token:
    required: true
    description: Github token to use for api calls
runs:
  using: composite
  
  steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Hydrate issue template
      id: hydrate
      env:
        # Later, we'll derive these from input variables
        environment: ldx-prod (DI)
        proposed_end_date_time: 2023/11/21 12:30
        proposed_start_date_time: 2023/11/21 12:15
        SLA_IMPACTS: SOME-IMPACTS
        MAINTENANCE_SEE_AFTER: |
          1. CHECK THIS
          2. CHECK THAT
          3. CHECK AGAIN
        USERS_SEE_AFTER: SEE STUF
        DEPLOYMENT_STEPS: |
          1. DRINK TOO MUCH COFFEE
          2. CLOSE EYES & HIT DEPLOY
          3. IMMEDIETELY FLEE AREA
        POST_DEPLOYMENT_VERIFICATION_STEPS: |
          1. CALL IN SICK
          2. CALL IN DEAD
        ROLLBACK_STEPS: |
          1. BREAK GLASS (EMERGENCY)
          2. YELL AT WHOMEVER COMES ACROSS YOUR PATH       
      run: |
        body=$(cat ./body-template.md | sed -e 's/\b\_\_/${/g' -e 's/\_\_\b/}/g' | envsubst)
        echo "value<<EOF" >> $GITHUB_OUTPUT
        echo "$body" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT          
      shell: bash
    - name: Create the issue
      env:
        proposed_start_date_time: 2023/11/21 12:15
        version: '23.12.4'
        GITHUB_TOKEN: ${{ inputs.gh-token }}
      id: create-issue
      run: >
        gh api /repos/${{ github.repository }}/issues
        --method POST
        -f title='[MR] Promote Lighthouse Hub ${{ env.version }} to Production (${{ env.proposed_start_date_time }} EST)'
        -f body='${{ steps.hydrate.outputs.value }}'
        -f "assignees[]=mhaley37"
      shell: bash