name: Create new MR
description: Create new maintenance request issue


inputs:
  gh-token:
    required: true
    description: Github token to use for api calls
  old-version:
    required: true
    description: The current version of the app ibeing supplanted in production  
  new-version:
    required: true
    description: The version of the app to deploy to production
outputs:
  issue-number:
    description: The number of the issue created
    value: ${{ steps.create-issue.outputs.data && fromJson(steps.create-issue.outputs.data).number }}
  url: 
    description: The URL to the issue
    value: ${{ steps.create-issue.outputs.data && fromJson(steps.create-issue.outputs.data).url }}


runs:
  using: composite
  
  steps:
    
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup ENV values
      env:
        # TODO: Testing only, set to America/New_York
        TZ: America/Los_Angeles
      run: |
        if [[ $(date +%H) < 10 ]]
        then
          echo "Will move before 10!"
          start-time="$(date + %F) 14:00 ET"
          end-time="$(date + %F) 14:30 ET"
        else
          echo "Will move tomorrow!"
          start-time="$(date -d "tomorrow" +%F) 10:00"
          end-time="$(date -d "tomorrow" +%F) 13:00"
        fi
        echo "proposed_end_date_time=${end-time}" >> $GITHUB_ENV
        echo "proposed_start_date_time=${start-time}" >> $GITHUB_ENV
        echo "NEW_VERSION=${{ inputs.new-version}}" >> $GITHUB_ENV
        echo "OLD_VERSION=${{ inputs.old-version}}" >> $GITHUB_ENV
      shell: bash
    - name: Hydrate issue template 
      id: hydrate-template-body
      run: |
        body=$(cat ./.github/actions/create-maintenance-request/mr-body-template.md | sed -e 's/\b\_\_/${/g' -e 's/\_\_\b/}/g' | envsubst)
        echo "value<<EOF" >> $GITHUB_OUTPUT
        echo "$body" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT          
      shell: bash 
    # This action needs parmeters to be specified in very exact ways, see https://github.com/marketplace/actions/github-api-request#inputs
    - name: Create Maintenance Request Issue
      uses: octokit/request-action@v2.x
      id: create-issue
      with:
        route: POST /repos/{owner}/{repo}/issues
        owner: mhaley3733
        repo: mhaley37
        assignees: '[mhaley37]'
        labels: '[lhdi,maintenance-request]'
        body: |
          |
          ${{ steps.hydrate-template-body.outputs.value }}
        # A string starting with `[ is treated special so need to break it out like this 
        title: |
          |
          [MR] Promote Lighthouse Hub ${{ env.NEW_VERSION }} to Production (${{ env.proposed_start_date_time }} EST)          
      env:
        GITHUB_TOKEN: ${{ inputs.gh-token }}
