name: Delete Old Workflow Runs
description: Deletes old GitHub Workflow runs that are no longer needed

outputs:
  deleted-runs:
    description: Array of objects each containing each run that was deleted
runs:
  using: node16
  main: index.js
