name: Test Failures

on:
  push:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  check-changed-files:
    name: Check changd files
    runs-on: ubuntu-latest
    steps:

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35
        with:
          files: |
            README.md

      - name: Did anything change
        if: steps.changed-files.outputs.any_changed == 'true'          
        run: |
          echo "files have been changed!"
