name: Test Failures

on:
  push:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  check-changed-files:
    name: Check changd files
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3
        with:
          # TODO: Get the preceeding commit sha
          fetch-depth: 2
          
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35

      - name: Did anything change
        if: steps.changed-files.outputs.any_changed == 'true'          
        run: |
          echo "files have been changed!"

      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
          done
