name: Test Failures

on:
  workflow_dispatch:
    inputs:
      token:
        required: false
        default: ''

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  pr-check:
    name: Check if PR closed or merged
    runs-on: ubuntu-latest
    env:
      TOKEN: ${{ inputs.token != '' && inputs.token || secrets.GH_TOKEN }}
    steps:
      - name: step
        run: |
          echo "PR check" 
          echo " My token is ${{ env.TOKEN }} "
