name: Test Failures

on:
  push:
  workflow_dispatch:

env:
  NAME: mike
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  pr-check:
    name: Check if PR closed or merged
    runs-on: ubuntu-latest
    env:
      TOKEN: ${{ env.name != '' && env.name || secrets.GH_TOKEN }}
    steps:
      - name: step
        run: |
          echo "PR check" 
          echo " My token is ${{ env.TOKEN }} "
