name: See Changed Files

on:
  push:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  check-changed-files:
    name: Check changd files
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3
        with:
          # TODO: Get the preceeding commit sha
          fetch-depth: 2

      - name: Get image dependency file paths 
        id: get-file-depend-paths
        run: |
          {
            echo 'paths<<EOF'
            echo "mike"
            echo "bill"
            echo "brian"
            echo EOF
          } >> "$GITHUB_ENV"
        #run: echo "paths=$(jq 'map(select(.["short-name"] == "frontend")) | .[0] | .["file-dependencies"] | .[]' docker-images.json)" >> $GITHUB_ENV
        shell: bash

      # - name: Get file depend paths
      #   id: get-file-depend-paths
      #   # file_paths=$(jq 'map(select(.["short-name"] == "frontend")) | .[0] | .["file-dependencies"] | .[]' docker-images.json)
       
      #   run: |
      #     echo "paths=hello" >> $GITHUB_ENV
      #   shell: bash
      - name: Output file names
        run: echo ${{ steps.get-file-depend-paths.outputs.paths }}
      - name: Get parsed file paths
        run: |
          for path in ${{ steps.get-file-depend-paths.outputs.paths }}
          do
            echo "File is $path"
          end
        shell: bash

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35

      - name: Get special changed files
        id: special-changed-files
        uses: tj-actions/changed-files@v35
        with:
          files: |
            package.json
            yarn.lock
            backend/**

      - name: Did anything change
        if: steps.changed-files.outputs.any_changed == 'true'          
        run: |
          echo "files have been changed!"


      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
          done
      - name: List all SPECIAL changed files
        run: |
            for file in ${{ steps.special-changed-files.outputs.all_changed_files }}; do
              echo "special $file was changed"
            done          