name: See Changed Files

on:
  push:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  check-changed-files:
    name: Check changd files
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3
        with:
          # TODO: Get the preceeding commit sha
          fetch-depth: 2

      # ALL
      - name: Get ALL changed files
        id: changed-files
        uses: tj-actions/changed-files@v35
          
      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
          done
               
      # NEW
      - name: Get image dependency file paths output to file (new)
        id: get-file-depend-paths-file
        run: jq -r 'map(select(.["short-name"] == "frontend")) | .[0] | .["file-dependencies"] | .[]' docker-images.json > paths.txt
        shell: bash


      - name: Get special changed files from file (new)
        id: special-changed-files-file
        uses: tj-actions/changed-files@v35
        with:
          files_from_source_file: ./paths.txt

      - name: List all SPECIAL changed files (new)
        run: |
            for file in ${{ steps.special-changed-files-file.outputs.all_changed_files }}; do
              echo "special $file was changed"
            done   

      # OLD FLOW
      - name: Get image dependency file paths  (old)
        id: get-file-depend-paths
        run: |
          {
            echo 'paths<<EOF'
            echo $(jq -r 'map(select(.["short-name"] == "frontend")) | .[0] | .["file-dependencies"] | .[]' docker-images.json)
            echo EOF
          } >> "$GITHUB_OUTPUT"        
        shell: bash

      - name: Get special changed files (old)
        id: special-changed-files
        uses: tj-actions/changed-files@v35
        with:
          files: ${{ steps.get-file-depend-paths.outputs.paths }}
          files_separator: " "

      - name: List all SPECIAL changed files (old)
        run: |
            for file in ${{ steps.special-changed-files.outputs.all_changed_files }}; do
              echo "special $file was changed"
            done   
      - name: Should we rebuild?!?!?!?
        if: steps.special-changed-files.outputs.any_changed == 'true'
        run: |
          echo "Stuff has changed, rebuild!!!!"