name: create new issue

on: 
  push:
  workflow_dispatch:

jobs:
  create-issue:
    name: Create a new issue
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Create issue
        uses: './.github/actions/create-maintenance-request'
        with:
          gh-token: ${{ github.token}}