name: Test finding PRs by label
on:
  push:
  workflow_dispatch:
    inputs:
      label:
        description: Label to search for
        type: string
        required: false
        
jobs:
  check-for-update-pr:
    runs-on: ubuntu-latest
    outputs:
      exists: ${{ fromJson(steps.count-label-prs.outputs.data).repository.pullRequests.totalCount > 0 }}
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
         
      - uses: octokit/graphql-action@v2.x
        name: Count PRs by label
        id: count-label-prs
        with:
          query: |
            query($owner: String!, $repo: String!, $labels: [String!] ) {
              repository(owner: $owner, name: $repo) {
                pullRequests(labels: $labels], states: OPEN ) {
            		 totalCount
                }
              }
            }
          variables: |
            owner: ${{ github.repository_owner }}
            repo: ${{ github.event.repository.name }}
            labels: '["backstage-bump"]'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  post-step:
    runs-on: ubuntu-latest  
    needs: check-for-update-pr
    steps:
      - name: Run only if open PR already
        if: fromJson(needs.check-for-update-pr.outputs.exists)
        shell: bash
        run: |
          echo If I am here it means there is an open PR by label backstage-bump!
