name: Test
on:
  workflow_dispatch:
    inputs:
      gh-pages:
        description: "Flag used to enable gh-pages deployment"
        default: " "
        required: false
jobs:
  deploy-gh-pages:
    if: ${{ inputs.gh-pages }} 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: ${{ env.REPO }}
          token: ${{ env.TOKEN }}
          ref: ${{ inputs.branch }}
