name: Matrix Test
on:
  workflow_dispatch:
    inputs:
      browser-name:
        description: 'Name of browser to run tests'
        # TODO: See if can make true IF env == local....think not.
        required: false    
      env:
        # expects "local" (default) or dev, qa, sandbox, prod
        default: local
        description: The environment to test
        required: false    
      type:
        # expect "browser" or "integration"
        default: browser
        required: false
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: validate-input
      run: |
        if [ ${{ inputs.env == 'local' && !inputs.browser }} ]
        then
          echo "invalid"
        else
          echo "Valid."
        fi
      
    - name: test step
      run: |
        echo "cy:run${{ inputs.type == 'integration' && ':'  || '' }}${{ inputs.type == 'integration' && inputs.type  || '' }}"
        echo "cy:run${{ inputs.type == 'integration' && ':integration' || '' }}"
