name: PR workflow

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  echo:
    name: Echo PR check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: echo
        run: |
          echo "Hello, pull request just happened!"
