name: Review workflow

on:
  pull_request_review:
  workflow_dispatch:

jobs:
  should-run:
    name: Check if should run
    runs-on: ubuntu-latest
    outputs:
      should-run: "false"
    steps:
      - name: setup
        id: get-repo-name
        run: |
          echo name is ${{ github.repository }}
          echo "town=pembroke" >> "$GITHUB_OUTPUT"
          echo "name=${{ github.repository }}" >> "$GITHUB_OUTPUT"
          echo "name2=$(echo ${{ github.repository }} | cut -d '/' -f 2 )" >> "$GITHUB_OUTPUT"
      - run: |
          echo ${{ steps.get-repo-name.output.town }}
          echo ${{ steps.get-repo-name.output.name }}
          echo ${{ steps.get-repo-name.output.name2 }}
      - uses: octokit/request-action@v2.1.0
        id: get_latest_release
        with:
          route: /repos/{owner}/{repo}/pulls/{pull_number}
          owner: ${{ github.repository_owner }}
          repo: ${{ steps.get-repo-name.outputs.name2 }}
          pull_number: ${{ github.event.pull_request.number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: "echo PR data!: '${{ steps.get_latest_release.outputs.data }}'"
          
  echo:
    name: Echo review check
    needs: [should-run]
    runs-on: ubuntu-latest
    if: fromJson(needs.should-run.outputs.should-run)
    steps:
      - uses: actions/checkout@v3
      - name: echo
        run: |
          echo "Hello, a PR review just happened!"
