name: Review workflow

on:
  # TODO: Remove
  push:
  pull_request_review:
  workflow_dispatch:

jobs:
  should-run:
    name: Check if should run
    runs-on: ubuntu-latest
    outputs:
      should-run: "false"
    steps:
      - name: setup
        id: get-repo-name
        run: echo "name=$(echo ${{ github.repository }} | cut -d '/' -f 2 )" >> "$GITHUB_OUTPUT"
      - uses: octokit/request-action@v2.1.0
        id: get_latest_release
        with:
          route: /repos/{owner}/{repo}/pulls/{pull_number}/reviews
          #owner: ${{ github.repository_owner }}
          #repo: ${{ steps.get-repo-name.outputs.name }}
          #pull_number: ${{ github.event.pull_request.number }}
          owner: department-of-veterans-affairs
          repo: lighthouse-developer-portal
          pull_number: 2140        
        env:
          GITHUB_TOKEN: ${{ secrets.SUPER_TOKEN }}
      - run: "echo PR data!: '${{ steps.get_latest_release.outputs.data }}'"
      - uses: octokit/graphql-action@v2.x
        id: count-approved-reviews
        with:
          query: |
            query($owner:String!,$repo:String!,$number:Int!) {
              repository(owner:$owner,name: $repo) {
                pullRequest(number:$number) {
                  reviews(states:APPROVED) {
                    totalCount
                  }
                }
              }
            }
          # TODO: Check this, might have issue with pr number being a string
          variables: |
            owner: department-of-veterans-affairs
            repo: lighthouse-developer-portal
            number: 2140
        env:
          GITHUB_TOKEN: ${{ secrets.SUPER_TOKEN }}
      - run: "echo graphql data: '${{ steps.count-approved-reviews.outputs.data }}'"          
          
  echo:
    name: Echo review check
    needs: [should-run]
    runs-on: ubuntu-latest
    if: fromJson(needs.should-run.outputs.should-run)
    steps:
      - uses: actions/checkout@v3
      - name: echo
        run: |
          echo "Hello, a PR review just happened!"
