name: Review workflow

on:
  # TODO: Remove
  push:
  pull_request_review:
  workflow_dispatch:

jobs:
  should-run:
    name: Check if should run
    runs-on: ubuntu-latest
    outputs:
      should-run: "false"
    steps:
      - name: setup
        id: get-repo-name
        run: echo "name=$(echo ${{ github.repository }} | cut -d '/' -f 2 )" >> "$GITHUB_OUTPUT"

      - uses: octokit/graphql-action@v2.x
        id: count-approved-reviews
        with:
          query: |
            query($owner:String!,$repo:String!,$number:Int!) {
              repository(owner:$owner,name: $repo) {
                pullRequest(number:$number) {
                  reviews(states:APPROVED) {
                    totalCount
                  }
                }
              }
            }
          # TODO: Check this, might have issue with pr number being a string
          #owner: ${{ github.event.repository.owner.name }}
          #repo: ${{ steps.get-repo-name.outputs.name }} or ${{ github.event.repository.name.}}
          #number: ${{ github.event.pull_request.number }}          
          variables: |
            owner: department-of-veterans-affairs
            repo: lighthouse-developer-portal
            number: 2140
        env:
          GITHUB_TOKEN: ${{ secrets.SUPER_TOKEN }}
      - run: "echo ${{ fromJson(steps.count-approved-reviews.outputs.data).repository.pullRequest.reviews.totalCount }}"
  echo:
    name: Echo review check
    needs: [should-run]
    runs-on: ubuntu-latest
    if: fromJson(needs.should-run.outputs.should-run)
    steps:
      - uses: actions/checkout@v3
      - name: echo
        run: |
          echo "Hello, a PR review just happened!"
