name: Review workflow

on:
  pull_request_review:
  workflow_dispatch:

jobs:
  should-run:
    name: Check if should run
    runs-on: ubuntu-latest
    outputs:
      should-run: false
    steps:
      - name: check
        run: |
          echo "Checking stuff about PR, id: ${{ github.event.pull_request.number }}"
          echo "Checking to see if should run these checks"
      - uses: octokit/request-action@v2.x
        id: get_latest_release
        with:
          route: /repos/{owner}/{repo}/pulls/{pull_number}
          owner: ${{ github.repository_owner }}
          repo: ${{ github.repository }}
          pull_number: ${{ github.event.pull_request.number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: "echo PR data!: '${{ steps.get_latest_release.outputs.data }}'"
          
  echo:
    name: Echo review check
    needs: [should-run]
    runs-on: ubuntu-latest
    if: needs.should-run.outputs.should-run
    steps:
      - uses: actions/checkout@v3
      - name: echo
        run: |
          echo "Hello, a PR review just happened!"
