name: Daily jobs

on:
  workflow_dispatch:

jobs:
  delete-workflows:
    name: Delete old workflow runs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up node
        uses: actions/setup-node@v3
        with:
          cache: yarn
          check-latest: true
          node-version: 16      
      - name: yarn
        run: yarn install
        shell: bash
      - name: Delete old workflow runs
        id: list
        uses: ./.github/actions/delete-old-workflows
        # TODO: CHECK OUT ACTION SPECIFIC AUTH STRATEGY
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Display output
        run: |
          echo "cmon-man ${{ steps.list.outputs.deleted-runs }}"
          echo 'testing ${{ steps.list.outputs.test }}'
        shell: bash