name: Daily jobs

on:
  push:
  workflow_dispatch:

jobs:
  delete-workflows:
    name: Delete old workflow runs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up node
        uses: actions/setup-node@v3
        with:
          cache: yarn
          check-latest: true
          node-version: 16      
      - name: Delete old workflows
        id: list
        uses: ./.github/actions/delete-old-workflows