name: Test needs dependencies

on:
  workflow_dispatch:
    inputs:
      skip-needs-job:
        description: True if should skip job other jobs are dependent on
        default: false
        type: boolean
        required: false

defaults:
  run:
    shell: bash

jobs:

  optional-job:
    name: Job that may not run, that other jobs are dependent on
    if: ${{ !inputs.skip-needs-job }}
    runs-on: ubuntu-22.04
    steps:
      - name: No Op
        run: echo "optional-job has run"

  always-job:
    name: Always run job
    needs: [ optional-job ]
    if: |
      !failure()
      && !cancelled()
    runs-on: ubuntu-22.04
    steps:
      - name: No Op
        run: echo "always-job has run"
    
  last-job:
    name: Runs after always-job
    needs: [ always-job ]
    runs-on: ubuntu-22.04
    steps:
      - name: No Op
        run: echo "last-job has run"

  last-job-always:
    name: Runs after always-job, ALWAYS
    needs: [ always-job ]
    runs-on: ubuntu-22.04
    if: always()
    steps:
    - name: No Op
      run: echo "last-job has run"

  last-job-not-fail:
    name: Runs after always-job, if non fail non cancel
    if: |
      !failure()
      && !cancelled()    
    needs: [ always-job ]
    runs-on: ubuntu-22.04
    steps:
    - name: No Op
      run: echo "last-job has run"             